// <auto-generated />
using System;
using DataCreationMicroservice.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataCreationMicroservice.Migrations
{
    [DbContext(typeof(StockMarketContext))]
    partial class StockMarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockMarketCharting.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BoardOfDirectors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectorID")
                        .HasColumnType("int");

                    b.Property<double>("Turnover")
                        .HasColumnType("float");

                    b.HasKey("CompanyId");

                    b.HasIndex("SectorID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("StockMarketCharting.Models.IPODetail", b =>
                {
                    b.Property<int>("IPODetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("OpenDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerShare")
                        .HasColumnType("float");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockExchangeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalNumOfShares")
                        .HasColumnType("int");

                    b.HasKey("IPODetailID");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("StockExchangeId");

                    b.ToTable("IPODetails");
                });

            modelBuilder.Entity("StockMarketCharting.Models.Sector", b =>
                {
                    b.Property<int>("SectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectorID");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("StockMarketCharting.Models.StockExchange", b =>
                {
                    b.Property<string>("StockExchangeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockExchangeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockExchangeID");

                    b.ToTable("StockExchanges");
                });

            modelBuilder.Entity("StockMarketCharting.Models.StockExchangeCompany", b =>
                {
                    b.Property<string>("StockExchangeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.HasKey("StockExchangeId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("StockExchangeCompanies");
                });

            modelBuilder.Entity("StockMarketCharting.Models.StockPrice", b =>
                {
                    b.Property<int>("StockPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<double>("CurrentPrice")
                        .HasColumnType("float");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockExchangeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockPriceId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StockExchangeId");

                    b.ToTable("StockPrices");
                });

            modelBuilder.Entity("StockMarketCharting.Models.Company", b =>
                {
                    b.HasOne("StockMarketCharting.Models.Sector", "Sector")
                        .WithMany("Companies")
                        .HasForeignKey("SectorID");
                });

            modelBuilder.Entity("StockMarketCharting.Models.IPODetail", b =>
                {
                    b.HasOne("StockMarketCharting.Models.Company", "Company")
                        .WithOne("IPODetail")
                        .HasForeignKey("StockMarketCharting.Models.IPODetail", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMarketCharting.Models.StockExchange", "StockExchange")
                        .WithMany("IPODetails")
                        .HasForeignKey("StockExchangeId");
                });

            modelBuilder.Entity("StockMarketCharting.Models.StockExchangeCompany", b =>
                {
                    b.HasOne("StockMarketCharting.Models.Company", "Company")
                        .WithMany("StockExchangeCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMarketCharting.Models.StockExchange", "StockExchange")
                        .WithMany("StockExchangeCompanies")
                        .HasForeignKey("StockExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockMarketCharting.Models.StockPrice", b =>
                {
                    b.HasOne("StockMarketCharting.Models.Company", "Company")
                        .WithMany("StockPrices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMarketCharting.Models.StockExchange", "StockExchange")
                        .WithMany("StockPrices")
                        .HasForeignKey("StockExchangeId");
                });
#pragma warning restore 612, 618
        }
    }
}
